### ISSUE TITLE
/donate addvc doesnt work.

### ISSUE THREAD

**Issue by FuZeEclipse** [aman207/DonatorExpress#10]
2013-07-17 17:58:35 [INFO] FuZeEclipse issued server command: /donate addvc FuZeEclipse 100
2013-07-17 17:58:35 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'donate' in plugin DonatorExpress v0.6.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
    at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:964)
    at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:882)
    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:839)
    at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
    at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:118)
    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
    at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NullPointerException
    at net.targetcraft.donatorexpress.CommandListener.onCommand(CommandListener.java:295)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

**Comment by aman207** [comment]
You did not setup your database correctly. If you are using cpanel, make sure that you are allowing outside connections.
